export const testData = {
    SPY: {
        symbol: 'SPY',
        exchange: 'NYSE Arca',
        name: 'SPDR S&P 500 ETF Trust',
        date: '2019-06-29',
        type: 'et',
        iexId: 'IEX_4D3735424E4B2D52',
        region: 'US',
        currency: 'USD',
        isEnabled: true,
        latestPrice: 293,
        latestUpdate: 'June 28th 2019, 4:00:00 pm ET',
        latestSource: 'Close',
        latestVolume: 57810644,
        open: 292.57,
        openTime: 'June 28th 2019, 9:30:00 am ET',
        close: 293,
        closeTime: 'June 28th 2019, 4:00:00 pm ET',
        previousClose: 291.5,
        change: 1.5,
        changePercent: 0.515,
        high: 293.19,
        low: 292.01,
        extendedPrice: 293,
        extendedPriceTime: 'June 29th 2019, 7:59:59 pm ET',
        extendedChange: 0,
        extendedChangePercent: 0,
        avgTotalVolume: 69279551,
        companyName: 'SPDR S&P 500 ETF Trust',
        securityName: 'SPDR S&P 500 ETF Trust',
        longDescription:
            'SPDR S&P 500 ETF Trust is an Exchange traded fund. The fund seeks to provide investment results that, before expenses, correspond generally to the price and yield performance of the S&P 500® Index. The S&P 500® Index is composed of five hundred selected stocks. SPDR S&P 500 ETF Trust was founded on January 22, 1993 and is headquartered in New York, NY.',
        industry: 'Investment Trusts/Mutual Funds',
        sector: 'Miscellaneous',
        website: 'http://www.spdrs.com',
        ceo: '',
        employees: ''
    },
    AAPL: {
        symbol: 'AAPL',
        exchange: 'NASDAQ',
        name: 'Apple Inc.',
        date: '2019-06-29',
        type: 'cs',
        iexId: 'IEX_4D48333344362D52',
        region: 'US',
        currency: 'USD',
        isEnabled: true,
        latestPrice: 197.92,
        latestUpdate: 'June 28th 2019, 4:00:00 pm ET',
        latestSource: 'Close',
        latestVolume: 31063165,
        open: 198.61,
        openTime: 'June 28th 2019, 9:30:00 am ET',
        close: 197.92,
        closeTime: 'June 28th 2019, 4:00:00 pm ET',
        previousClose: 199.74,
        change: -1.82,
        changePercent: -0.911,
        high: 199.495,
        low: 197.05,
        extendedPrice: 197.99,
        extendedPriceTime: 'June 29th 2019, 7:59:45 pm ET',
        extendedChange: 0.07,
        extendedChangePercent: 0.034999999999999996,
        avgTotalVolume: 26991977,
        companyName: 'Apple, Inc.',
        securityName: 'Apple Inc.',
        longDescription:
            'Apple, Inc. engages in the design, manufacture, and marketing of mobile communication, media devices, personal computers, and portable digital music players. It operates through the following geographical segments: Americas, Europe, Greater China, Japan, and Rest of Asia Pacific. The Americas segment includes North and South America. The Europe segment consists of European countries, as well as India, the Middle East, and Africa. The Greater China segment comprises of China, Hong Kong, and Taiwan. The Rest of Asia Pacific segment includes Australia and Asian countries. The company was founded by Steven Paul Jobs, Ronald Gerald Wayne, and Stephen G. Wozniak on April 1, 1976 and is headquartered in Cupertino, CA.',
        industry: 'Telecommunications Equipment',
        sector: 'Electronic Technology',
        website: 'http://www.apple.com',
        ceo: 'Timothy Donald Cook',
        employees: '132000'
    },
    COF: {
        symbol: 'COF',
        exchange: 'New York Stock Exchange',
        name: 'Capital One Financial Corporation',
        date: '2019-06-29',
        type: 'cs',
        iexId: 'IEX_4C443057595A2D52',
        region: 'US',
        currency: 'USD',
        isEnabled: true,
        latestPrice: 90.74,
        latestUpdate: 'June 28th 2019, 4:04:28 pm ET',
        latestSource: 'Close',
        latestVolume: 3156332,
        open: 90.21,
        openTime: 'June 28th 2019, 9:30:00 am ET',
        close: 90.74,
        closeTime: 'June 28th 2019, 4:04:28 pm ET',
        previousClose: 89.33,
        change: 1.41,
        changePercent: 1.5779999999999998,
        high: 91.09,
        low: 89.34,
        extendedPrice: 92,
        extendedPriceTime: 'June 29th 2019, 7:55:07 pm ET',
        extendedChange: 1.26,
        extendedChangePercent: 1.389,
        avgTotalVolume: 1740513,
        companyName: 'Capital One Financial Corp.',
        securityName: 'Capital One Financial Corporation',
        longDescription:
            'Capital One Financial Corp. is a financial holding company, which engages in the provision of financial products and services. It operates through the following segments: Credit Card, Consumer Banking, and Commercial Banking. The Credit Card segment offers domestic consumer and small business card lending, and international card lending businesses. The Consumer Banking segment consists of branch-based lending and deposit gathering activities for consumers and small businesses. The Commercial Banking segment comprises of lending, deposit gathering and treasury management services to commercial real estate and commercial and industrial customers. The company was founded by Richard D. Fairbank on July 21, 1994 and is headquartered in McLean, VA.',
        industry: 'Major Banks',
        sector: 'Finance',
        website: 'http://www.capitalone.com',
        ceo: 'Richard D. Fairbank',
        employees: '47600'
    },
    MTCH: {
        symbol: 'MTCH',
        exchange: 'NASDAQ',
        name: 'Match Group Inc.',
        date: '2019-06-29',
        type: 'cs',
        iexId: 'IEX_5246383657592D52',
        region: 'US',
        currency: 'USD',
        isEnabled: true,
        latestPrice: 67.27,
        latestUpdate: 'June 28th 2019, 4:00:01 pm ET',
        latestSource: 'Close',
        latestVolume: 1753353,
        open: 68.12,
        openTime: 'June 28th 2019, 9:30:00 am ET',
        close: 67.27,
        closeTime: 'June 28th 2019, 4:00:01 pm ET',
        previousClose: 68.23,
        change: -0.96,
        changePercent: -1.407,
        high: 68.79,
        low: 67.23,
        extendedPrice: 67.04,
        extendedPriceTime: 'June 29th 2019, 7:22:33 pm ET',
        extendedChange: -0.23,
        extendedChangePercent: -0.34199999999999997,
        avgTotalVolume: 1610632,
        companyName: 'Match Group, Inc.',
        securityName: 'Match Group, Inc.',
        longDescription:
            'Match Group, Inc. engages in providing dating products. Its brands include: Match, Tinder, PlentyOfFish, Meetic, OkCupid, Pairs, Twoo, OurTime, BlackPeopleMeet, and LoveScout24. It operates through the following segments: Dating and Non-Dating. The Dating segment provides dating products. The Non-Dating segment offers a variety of education services including test preparation, academic tutoring, and college counseling services. The company was founded on February 12, 2009 and is headquartered in Dallas, TX.',
        industry: 'Internet Software/Services',
        sector: 'Technology Services',
        website: 'http://www.matchgroupinc.com',
        ceo: 'Amanda W. Ginsberg',
        employees: '1500'
    }
}

export const usersListOfTickers = {
    AAPL: 1,
    SPY: 1,
    COF: 1,
    MTCH: 1
}
